# Generated by Django 3.0.14 on 2025-01-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
