# Generated by Django 3.0.14 on 2025-01-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_crop_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=100)),
                ('CROP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop')),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Expert')),
            ],
        ),
    ]
