# Generated by Django 3.0.14 on 2025-01-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250113_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmer_register',
            new_name='Farmer',
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='CROP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop'),
        ),
    ]
