# Generated by Django 2.0 on 2025-01-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20250115_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farmer')),
            ],
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='CROP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop'),
        ),
    ]
