# Generated by Django 2.0 on 2025-01-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20250127_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='CROP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop'),
        ),
    ]
