# Generated by Django 2.0 on 2025-01-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20250127_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='CROP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop'),
        ),
    ]
