# Generated by Django 2.0 on 2025-01-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20250127_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_price', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('BOOKING_CHILD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Booking_child')),
            ],
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='CROP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop'),
        ),
        migrations.AddField(
            model_name='booking_child',
            name='BOOKING_MASTER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Booking_master'),
        ),
    ]
