# Generated by Django 2.0 on 2025-01-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20250127_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farmer')),
            ],
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='CROP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop'),
        ),
    ]
