# Generated by Django 2.0 on 2025-01-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20250128_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='FARMER',
        ),
        migrations.AddField(
            model_name='doubt',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='CROP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Crop'),
        ),
    ]
